name: СШ

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up cppcheck
        run: sudo apt-get install -y cppcheck
      
      - name: Set up CMake
        run: sudo apt install cmake
      
      - name: Set up Valgrind
        run: sudo apt-get install valgrind

      - name: Set up Doxygen
        run:  sudo apt-get install -y doxygen
      
      - name: Check source file
        run : make check_source_file
      
      - name: Check memory
        run: make check_source_file
      
      - name: Code formatting
        run: make format

      - name: Make docs
        run:  make docs
