name: СШ

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen

      - name: Make docs
        run: |
          make docs
