name: СШ

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'linear_data_structures/'
          doxyfile-path: 'docs'

      - name: Make docs
        run: |
          make install
          
      - name: Run linter
        run: make lint
